#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2021-11-07 21:08:53
# @Author  : Thanks for Yong Lee Tell me how to build this Package (${email})
# @Link    : ${link}
# @Version : $Id$

import random
money = 1000 
while money > 0 :
    debt = int (input('please put the money :'))
    needagain = False
    a = random.randint(1,6)
    b = random.randint(1,6)
    sum = a + b
    print ('you number is %d ' %sum)
    if sum == 7 or sum == 11:
        print ('you win')
        money += debt
        print ('now the money is %d' %money)
    elif (sum == 2 or sum == 3 or sum == 12 ):
        print ('you lose')
        money -= debt
        print ('now the money is %d' %money)
    else :
        needagain = True
        while needagain:
            needagain = False
            current = random.randint(1,6) + random.randint(1,6)
            print ('you need to go again and the nunber is %d' %current)
            if current == 7 :
                print ('you lose')
                money -= debt
                print ('now the money is %d' %money)
            elif current == sum:
                print ('you win')
                money += debt
                print ('now the money is %d' %money)
            else :
                sum = current
                needagain = True